# Generated by Django 4.2.6 on 2024-03-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Captcha',
        ),
    ]
