# Generated by Django 4.2.6 on 2024-03-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_delete_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='uuid.uuid.4', max_length=100, unique=True),
        ),
    ]
