# Generated by Django 4.2.6 on 2024-03-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_alter_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
