# Generated by Django 4.2.6 on 2024-03-22 17:01

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_remove_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to='auth/'),
        ),
    ]
