# Generated by Django 4.2.6 on 2024-03-07 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('auction', models.BooleanField(help_text='Отметьте, уместен ли торг', verbose_name='Торг')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('image', models.ImageField(blank=True, upload_to='online_shop/', verbose_name='Изображение')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'db_table': 'advertisements',
            },
        ),
    ]
