# Generated by Django 4.2.6 on 2024-03-22 17:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineshop',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to='auth/'),
        ),
    ]
